using ApiPOS.AppCode.Models.Entities;

namespace ApiPOS.AppCode.Models.Seeders
{
    public static class SeedProductos
    {
        public static void Seed(ApiPOS.AppCode.DBContext.AppDBContext context)
        {
            if (!context.Productos.Any())
            {
                var categoriaBebidas = context.Categorias.FirstOrDefault(c => c.Nombre == "Bebidas");
                var categoriaSnacks = context.Categorias.FirstOrDefault(c => c.Nombre == "Snacks");
                var categoriaLimpieza = context.Categorias.FirstOrDefault(c => c.Nombre == "Limpieza");

                var almacenPuerto = context.Almacenes.FirstOrDefault(a => a.Nombre == "Almacen Puerto");
                var almacenCentral = context.Almacenes.FirstOrDefault(a => a.Nombre == "Almacen Central");

                if (categoriaBebidas == null || almacenCentral == null)
                    return; // No se puede sembrar si faltan datos base


                var productos = new List<Producto>
                {
                    new Producto { Nombre = "Coca-Cola 1L", Descripcion = "Bebida gaseosa", PrecioLista = 1.80m, PrecioNormal = 1.60m, PrecioVenta = 1.50m, PrecioSinImpuesto = 1.30m, PrecioVentaSinDescuento = 1.60m, DescuentoPctje = 6, CodigoBarras = "1000000000001", Existencia = 100, UrlImagen = "imagenes/productos/coca1l.png", CategoriaId = 1, AlmacenId = 1 },
                    new Producto { Nombre = "Leche Deslactosada 1L", Descripcion = "Leche sin lactosa", PrecioLista = 1.50m, PrecioNormal = 1.40m, PrecioVenta = 1.30m, PrecioSinImpuesto = 1.10m, PrecioVentaSinDescuento = 1.40m, DescuentoPctje = 7, CodigoBarras = "1000000000002", Existencia = 80, UrlImagen = "imagenes/productos/leche1l.png", CategoriaId = 2, AlmacenId = 1 },
                    new Producto { Nombre = "Pan Integral 500g", Descripcion = "Pan saludable integral", PrecioLista = 1.20m, PrecioNormal = 1.10m, PrecioVenta = 1.00m, PrecioSinImpuesto = 0.90m, PrecioVentaSinDescuento = 1.10m, DescuentoPctje = 5, CodigoBarras = "1000000000003", Existencia = 60, UrlImagen = "imagenes/productos/panintegral.png", CategoriaId = 3, AlmacenId = 1 },
                    new Producto { Nombre = "Salchicha Viena 250g", Descripcion = "Salchicha tipo Viena", PrecioLista = 2.50m, PrecioNormal = 2.30m, PrecioVenta = 2.10m, PrecioSinImpuesto = 1.90m, PrecioVentaSinDescuento = 2.30m, DescuentoPctje = 8, CodigoBarras = "1000000000004", Existencia = 50, UrlImagen = "imagenes/productos/salchicha250.png", CategoriaId = 4, AlmacenId = 2 },
                    new Producto { Nombre = "Manzana Verde 1kg", Descripcion = "Fruta fresca", PrecioLista = 2.20m, PrecioNormal = 2.00m, PrecioVenta = 1.90m, PrecioSinImpuesto = 1.70m, PrecioVentaSinDescuento = 2.00m, DescuentoPctje = 5, CodigoBarras = "1000000000005", Existencia = 90, UrlImagen = "imagenes/productos/manzanaverde.png", CategoriaId = 5, AlmacenId = 2 },
                    new Producto { Nombre = "Papas Fritas 150g", Descripcion = "Snack crujiente", PrecioLista = 1.30m, PrecioNormal = 1.20m, PrecioVenta = 1.10m, PrecioSinImpuesto = 1.00m, PrecioVentaSinDescuento = 1.20m, DescuentoPctje = 8, CodigoBarras = "1000000000006", Existencia = 120, UrlImagen = "imagenes/productos/papas150.png", CategoriaId = 6, AlmacenId = 1 },
                    new Producto { Nombre = "Arroz 1kg", Descripcion = "Arroz grano largo", PrecioLista = 1.10m, PrecioNormal = 1.00m, PrecioVenta = 0.90m, PrecioSinImpuesto = 0.80m, PrecioVentaSinDescuento = 1.00m, DescuentoPctje = 10, CodigoBarras = "1000000000007", Existencia = 200, UrlImagen = "imagenes/productos/arroz1kg.png", CategoriaId = 7, AlmacenId = 1 },
                    new Producto { Nombre = "Detergente en Polvo 1kg", Descripcion = "Limpieza de ropa", PrecioLista = 2.50m, PrecioNormal = 2.30m, PrecioVenta = 2.00m, PrecioSinImpuesto = 1.80m, PrecioVentaSinDescuento = 2.30m, DescuentoPctje = 7, CodigoBarras = "1000000000008", Existencia = 80, UrlImagen = "imagenes/productos/detergentepolvo.png", CategoriaId = 8, AlmacenId = 1 },
                    new Producto { Nombre = "Shampoo 400ml", Descripcion = "Cuidado del cabello", PrecioLista = 3.50m, PrecioNormal = 3.20m, PrecioVenta = 3.00m, PrecioSinImpuesto = 2.70m, PrecioVentaSinDescuento = 3.20m, DescuentoPctje = 6, CodigoBarras = "1000000000009", Existencia = 70, UrlImagen = "imagenes/productos/shampoo400.png", CategoriaId = 9, AlmacenId = 1 },
                    new Producto { Nombre = "Paracetamol 500mg 20un", Descripcion = "Alivio del dolor y fiebre", PrecioLista = 2.00m, PrecioNormal = 1.80m, PrecioVenta = 1.60m, PrecioSinImpuesto = 1.40m, PrecioVentaSinDescuento = 1.80m, DescuentoPctje = 10, CodigoBarras = "1000000000010", Existencia = 100, UrlImagen = "imagenes/productos/paracetamol.png", CategoriaId = 10, AlmacenId = 2 },
                    new Producto { Nombre = "Audífonos Inalámbricos", Descripcion = "Bluetooth", PrecioLista = 25.00m, PrecioNormal = 23.00m, PrecioVenta = 22.00m, PrecioSinImpuesto = 20.00m, PrecioVentaSinDescuento = 23.00m, DescuentoPctje = 5, CodigoBarras = "1000000000011", Existencia = 30, UrlImagen = "imagenes/productos/audifonos.png", CategoriaId = 11, AlmacenId = 1 },
                    new Producto { Nombre = "Camiseta Talla M", Descripcion = "Ropa de algodón", PrecioLista = 10.00m, PrecioNormal = 9.00m, PrecioVenta = 8.00m, PrecioSinImpuesto = 7.00m, PrecioVentaSinDescuento = 9.00m, DescuentoPctje = 11, CodigoBarras = "1000000000012", Existencia = 60, UrlImagen = "imagenes/productos/camiseta.png", CategoriaId = 12, AlmacenId = 2 },
                    new Producto { Nombre = "Cartera Mujer", Descripcion = "Accesorio de moda", PrecioLista = 20.00m, PrecioNormal = 18.00m, PrecioVenta = 16.00m, PrecioSinImpuesto = 14.00m, PrecioVentaSinDescuento = 18.00m, DescuentoPctje = 11, CodigoBarras = "1000000000013", Existencia = 40, UrlImagen = "imagenes/productos/cartera.png", CategoriaId = 13, AlmacenId = 2 },
                    new Producto { Nombre = "Muñeca Barbie", Descripcion = "Juguete para niñas", PrecioLista = 15.00m, PrecioNormal = 14.00m, PrecioVenta = 13.00m, PrecioSinImpuesto = 11.00m, PrecioVentaSinDescuento = 14.00m, DescuentoPctje = 7, CodigoBarras = "1000000000014", Existencia = 50, UrlImagen = "imagenes/productos/barbie.png", CategoriaId = 14, AlmacenId = 2 },
                    new Producto { Nombre = "Martillo Acero", Descripcion = "Herramienta manual", PrecioLista = 8.00m, PrecioNormal = 7.50m, PrecioVenta = 7.00m, PrecioSinImpuesto = 6.00m, PrecioVentaSinDescuento = 7.50m, DescuentoPctje = 7, CodigoBarras = "1000000000015", Existencia = 40, UrlImagen = "imagenes/productos/martillo.png", CategoriaId = 15, AlmacenId = 1 },
                    new Producto { Nombre = "Cuaderno 100 Hojas", Descripcion = "Cuaderno escolar", PrecioLista = 1.50m, PrecioNormal = 1.30m, PrecioVenta = 1.20m, PrecioSinImpuesto = 1.00m, PrecioVentaSinDescuento = 1.30m, DescuentoPctje = 7, CodigoBarras = "1000000000016", Existencia = 100, UrlImagen = "imagenes/productos/cuaderno.png", CategoriaId = 16, AlmacenId = 1 },
                    new Producto { Nombre = "Croquetas Perro 2kg", Descripcion = "Alimento seco para perro", PrecioLista = 5.00m, PrecioNormal = 4.50m, PrecioVenta = 4.00m, PrecioSinImpuesto = 3.50m, PrecioVentaSinDescuento = 4.50m, DescuentoPctje = 11, CodigoBarras = "1000000000017", Existencia = 30, UrlImagen = "imagenes/productos/croquetas.png", CategoriaId = 17, AlmacenId = 2 },
                    new Producto { Nombre = "Almohada Suave", Descripcion = "Almohada para dormir", PrecioLista = 8.00m, PrecioNormal = 7.50m, PrecioVenta = 7.00m, PrecioSinImpuesto = 6.50m, PrecioVentaSinDescuento = 7.50m, DescuentoPctje = 6, CodigoBarras = "1000000000018", Existencia = 25, UrlImagen = "imagenes/productos/almohada.png", CategoriaId = 18, AlmacenId = 2 },
                    new Producto { Nombre = "Taladro Eléctrico", Descripcion = "Herramienta eléctrica", PrecioLista = 50.00m, PrecioNormal = 45.00m, PrecioVenta = 43.00m, PrecioSinImpuesto = 40.00m, PrecioVentaSinDescuento = 45.00m, DescuentoPctje = 4, CodigoBarras = "1000000000019", Existencia = 10, UrlImagen = "imagenes/productos/taladro.png", CategoriaId = 19, AlmacenId = 1 },
                    new Producto { Nombre = "Cerveza 355ml", Descripcion = "Bebida alcohólica", PrecioLista = 1.20m, PrecioNormal = 1.10m, PrecioVenta = 1.00m, PrecioSinImpuesto = 0.90m, PrecioVentaSinDescuento = 1.10m, DescuentoPctje = 9, CodigoBarras = "1000000000020", Existencia = 60, UrlImagen = "imagenes/productos/cerveza.png", CategoriaId = 20, AlmacenId = 2 },
                    new Producto { Nombre = "Aceite de Cocina 1L", Descripcion = "Aceite vegetal", PrecioLista = 2.20m, PrecioNormal = 2.00m, PrecioVenta = 1.90m, PrecioSinImpuesto = 1.70m, PrecioVentaSinDescuento = 2.00m, DescuentoPctje = 5, CodigoBarras = "1000000000021", Existencia = 70, UrlImagen = "imagenes/productos/aceite.png", CategoriaId = 1, AlmacenId = 1 },
                    new Producto { Nombre = "Azúcar 1kg", Descripcion = "Azúcar refinada", PrecioLista = 1.30m, PrecioNormal = 1.20m, PrecioVenta = 1.10m, PrecioSinImpuesto = 1.00m, PrecioVentaSinDescuento = 1.20m, DescuentoPctje = 8, CodigoBarras = "1000000000022", Existencia = 100, UrlImagen = "imagenes/productos/azucar.png", CategoriaId = 7, AlmacenId = 1 },
                    new Producto { Nombre = "Jabón de Tocador 125g", Descripcion = "Jabón corporal", PrecioLista = 1.00m, PrecioNormal = 0.90m, PrecioVenta = 0.85m, PrecioSinImpuesto = 0.75m, PrecioVentaSinDescuento = 0.90m, DescuentoPctje = 6, CodigoBarras = "1000000000023", Existencia = 150, UrlImagen = "imagenes/productos/jabon.png", CategoriaId = 8, AlmacenId = 1 },
                    new Producto { Nombre = "Queso Fresco 500g", Descripcion = "Lácteo", PrecioLista = 3.00m, PrecioNormal = 2.80m, PrecioVenta = 2.60m, PrecioSinImpuesto = 2.30m, PrecioVentaSinDescuento = 2.80m, DescuentoPctje = 7, CodigoBarras = "1000000000024", Existencia = 60, UrlImagen = "imagenes/productos/queso.png", CategoriaId = 2, AlmacenId = 1 },
                    new Producto { Nombre = "Cereal de Maíz 300g", Descripcion = "Desayuno", PrecioLista = 2.50m, PrecioNormal = 2.30m, PrecioVenta = 2.10m, PrecioSinImpuesto = 1.90m, PrecioVentaSinDescuento = 2.30m, DescuentoPctje = 9, CodigoBarras = "1000000000025", Existencia = 80, UrlImagen = "imagenes/productos/cereal.png", CategoriaId = 3, AlmacenId = 1 },
                    new Producto { Nombre = "Jugo de Naranja 1L", Descripcion = "Bebida natural", PrecioLista = 1.80m, PrecioNormal = 1.60m, PrecioVenta = 1.50m, PrecioSinImpuesto = 1.30m, PrecioVentaSinDescuento = 1.60m, DescuentoPctje = 6, CodigoBarras = "1000000000026", Existencia = 100, UrlImagen = "imagenes/productos/jugo.png", CategoriaId = 1, AlmacenId = 1 },
                    new Producto { Nombre = "Yogurt Natural 500ml", Descripcion = "Lácteo", PrecioLista = 2.00m, PrecioNormal = 1.80m, PrecioVenta = 1.70m, PrecioSinImpuesto = 1.50m, PrecioVentaSinDescuento = 1.80m, DescuentoPctje = 6, CodigoBarras = "1000000000027", Existencia = 90, UrlImagen = "imagenes/productos/yogurt.png", CategoriaId = 2, AlmacenId = 1 },
                    new Producto { Nombre = "Papel Higiénico 4 rollos", Descripcion = "Baño", PrecioLista = 3.00m, PrecioNormal = 2.70m, PrecioVenta = 2.50m, PrecioSinImpuesto = 2.30m, PrecioVentaSinDescuento = 2.70m, DescuentoPctje = 7, CodigoBarras = "1000000000028", Existencia = 120, UrlImagen = "imagenes/productos/papel.png", CategoriaId = 8, AlmacenId = 1 },
                    new Producto { Nombre = "Galletas de Chocolate 200g", Descripcion = "Snack dulce", PrecioLista = 1.50m, PrecioNormal = 1.30m, PrecioVenta = 1.20m, PrecioSinImpuesto = 1.00m, PrecioVentaSinDescuento = 1.30m, DescuentoPctje = 8, CodigoBarras = "1000000000029", Existencia = 110, UrlImagen = "imagenes/productos/galletas.png", CategoriaId = 6, AlmacenId = 1 },
                    new Producto { Nombre = "Toalla de Mano", Descripcion = "Baño", PrecioLista = 5.00m, PrecioNormal = 4.50m, PrecioVenta = 4.00m, PrecioSinImpuesto = 3.50m, PrecioVentaSinDescuento = 4.50m, DescuentoPctje = 11, CodigoBarras = "1000000000030", Existencia = 40, UrlImagen = "imagenes/productos/toalla.png", CategoriaId = 18, AlmacenId = 2 },
                    new Producto { Nombre = "iPhone 14 Pro", Descripcion = "Smartphone Apple 128GB", PrecioLista = 1200.00m, PrecioNormal = 1150.00m, PrecioVenta = 1100.00m, PrecioSinImpuesto = 1000.00m, PrecioVentaSinDescuento = 1150.00m, DescuentoPctje = 4, CodigoBarras = "2000000000001", Existencia = 15, UrlImagen = "imagenes/productos/iphone14pro.png", CategoriaId = 11, AlmacenId = 1 },
                    new Producto { Nombre = "Samsung Galaxy S23", Descripcion = "Smartphone Android 256GB", PrecioLista = 950.00m, PrecioNormal = 920.00m, PrecioVenta = 900.00m, PrecioSinImpuesto = 850.00m, PrecioVentaSinDescuento = 920.00m, DescuentoPctje = 3, CodigoBarras = "2000000000002", Existencia = 20, UrlImagen = "imagenes/productos/galaxys23.png", CategoriaId = 11, AlmacenId = 1 },
                    new Producto { Nombre = "iPad Air 10.9\" 64GB", Descripcion = "Tablet Apple", PrecioLista = 700.00m, PrecioNormal = 670.00m, PrecioVenta = 650.00m, PrecioSinImpuesto = 600.00m, PrecioVentaSinDescuento = 670.00m, DescuentoPctje = 3, CodigoBarras = "2000000000003", Existencia = 12, UrlImagen = "imagenes/productos/ipadair.png", CategoriaId = 11, AlmacenId = 1 },
                    new Producto { Nombre = "Lenovo ThinkPad E14", Descripcion = "Laptop 14\" Intel i5", PrecioLista = 850.00m, PrecioNormal = 820.00m, PrecioVenta = 800.00m, PrecioSinImpuesto = 750.00m, PrecioVentaSinDescuento = 820.00m, DescuentoPctje = 2, CodigoBarras = "2000000000004", Existencia = 10, UrlImagen = "imagenes/productos/thinkpad.png", CategoriaId = 11, AlmacenId = 1 },
                    new Producto { Nombre = "MacBook Pro 13\"", Descripcion = "Apple M1 256GB SSD", PrecioLista = 1300.00m, PrecioNormal = 1250.00m, PrecioVenta = 1200.00m, PrecioSinImpuesto = 1100.00m, PrecioVentaSinDescuento = 1250.00m, DescuentoPctje = 4, CodigoBarras = "2000000000005", Existencia = 8, UrlImagen = "imagenes/productos/macbookpro.png", CategoriaId = 11, AlmacenId = 1 },
                    new Producto { Nombre = "Monitor LG 24\" Full HD", Descripcion = "Monitor IPS 1080p", PrecioLista = 200.00m, PrecioNormal = 190.00m, PrecioVenta = 180.00m, PrecioSinImpuesto = 160.00m, PrecioVentaSinDescuento = 190.00m, DescuentoPctje = 5, CodigoBarras = "2000000000006", Existencia = 25, UrlImagen = "imagenes/productos/monitorlg.png", CategoriaId = 11, AlmacenId = 1 },
                    new Producto { Nombre = "Teclado Mecánico RGB", Descripcion = "Gaming teclado retroiluminado", PrecioLista = 90.00m, PrecioNormal = 85.00m, PrecioVenta = 80.00m, PrecioSinImpuesto = 70.00m, PrecioVentaSinDescuento = 85.00m, DescuentoPctje = 6, CodigoBarras = "2000000000007", Existencia = 40, UrlImagen = "imagenes/productos/teclado.png", CategoriaId = 11, AlmacenId = 1 },
                    new Producto { Nombre = "Mouse Inalámbrico Logitech", Descripcion = "Mouse Bluetooth", PrecioLista = 45.00m, PrecioNormal = 42.00m, PrecioVenta = 40.00m, PrecioSinImpuesto = 36.00m, PrecioVentaSinDescuento = 42.00m, DescuentoPctje = 5, CodigoBarras = "2000000000008", Existencia = 50, UrlImagen = "imagenes/productos/mouse.png", CategoriaId = 11, AlmacenId = 1 },
                    new Producto { Nombre = "Auriculares Sony WH-1000XM4", Descripcion = "Noise Cancelling", PrecioLista = 350.00m, PrecioNormal = 330.00m, PrecioVenta = 320.00m, PrecioSinImpuesto = 290.00m, PrecioVentaSinDescuento = 330.00m, DescuentoPctje = 3, CodigoBarras = "2000000000009", Existencia = 18, UrlImagen = "imagenes/productos/sonywh1000.png", CategoriaId = 11, AlmacenId = 1 },
                    new Producto { Nombre = "Cargador Rápido 20W", Descripcion = "USB-C Apple", PrecioLista = 35.00m, PrecioNormal = 32.00m, PrecioVenta = 30.00m, PrecioSinImpuesto = 28.00m, PrecioVentaSinDescuento = 32.00m, DescuentoPctje = 6, CodigoBarras = "2000000000010", Existencia = 100, UrlImagen = "imagenes/productos/cargador.png", CategoriaId = 11, AlmacenId = 1 },
                    new Producto { Nombre = "Disco Duro Externo 1TB", Descripcion = "USB 3.0", PrecioLista = 90.00m, PrecioNormal = 85.00m, PrecioVenta = 80.00m, PrecioSinImpuesto = 75.00m, PrecioVentaSinDescuento = 85.00m, DescuentoPctje = 6, CodigoBarras = "2000000000011", Existencia = 30, UrlImagen = "imagenes/productos/discoduro.png", CategoriaId = 11, AlmacenId = 1 },
                    new Producto { Nombre = "Tablet Samsung Galaxy Tab A8", Descripcion = "Tablet 10.5\" 64GB", PrecioLista = 280.00m, PrecioNormal = 260.00m, PrecioVenta = 250.00m, PrecioSinImpuesto = 230.00m, PrecioVentaSinDescuento = 260.00m, DescuentoPctje = 4, CodigoBarras = "2000000000012", Existencia = 15, UrlImagen = "imagenes/productos/taba8.png", CategoriaId = 11, AlmacenId = 1 },
                    new Producto { Nombre = "PC Gamer Ryzen 5", Descripcion = "Desktop con tarjeta gráfica", PrecioLista = 950.00m, PrecioNormal = 900.00m, PrecioVenta = 880.00m, PrecioSinImpuesto = 800.00m, PrecioVentaSinDescuento = 900.00m, DescuentoPctje = 2, CodigoBarras = "2000000000013", Existencia = 6, UrlImagen = "imagenes/productos/pcgamer.png", CategoriaId = 11, AlmacenId = 1 },
                    new Producto { Nombre = "Impresora Multifunción HP", Descripcion = "Imprime, escanea, copia", PrecioLista = 160.00m, PrecioNormal = 150.00m, PrecioVenta = 145.00m, PrecioSinImpuesto = 130.00m, PrecioVentaSinDescuento = 150.00m, DescuentoPctje = 3, CodigoBarras = "2000000000014", Existencia = 20, UrlImagen = "imagenes/productos/impresora.png", CategoriaId = 11, AlmacenId = 1 },
                    new Producto { Nombre = "Smartwatch Apple Watch SE", Descripcion = "GPS 44mm", PrecioLista = 320.00m, PrecioNormal = 310.00m, PrecioVenta = 300.00m, PrecioSinImpuesto = 270.00m, PrecioVentaSinDescuento = 310.00m, DescuentoPctje = 3, CodigoBarras = "2000000000015", Existencia = 12, UrlImagen = "imagenes/productos/applewatch.png", CategoriaId = 11, AlmacenId = 1 }
                 
                };

                context.Productos.AddRange(productos);
                context.SaveChanges();
            }
        }
    }
}
